version: '3'

services:
  frontend:
    build:
      context: .
    volumes:
      - ./:/opt/app:cached
    ports:
      - '3000:3000'
      - '24678:24678'
    command: sh -c "rm -rf '/tmp/nitro/' && yarn install && yarn dev"
